spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://catalog-db:3306/catalog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:catalog_user}
    password: ${SPRING_DATASOURCE_PASSWORD:catalog_pass}

  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:nacos:8848}  # Docker 环境使用容器名

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}